### ISSUE TITLE
Game crash while using gadgets

### ISSUE THREAD

**Issue by Feliixtc** [Direwolf20-MC/BuildingGadgets2#13] opened 2023-08-24 00:27 UTC
Minecraft Version: 1.20.1
Mod Version: 0.1.3
Using Optifine: No
Issue: Game frequently crashes when using gadgets, or even scrolling past them on the toolbar.

[This](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12424185/hs_err_pid8460.log) is the error log left after one of the crashes.

**Comment by Direwolf20-MC** [comment] 2023-08-24 01:22
These kinds of issues *usually* are memory related. Weird. Is there copy data on the gadgets ? Is it any particular gadget causing it, or all of them?

**Comment by Direwolf20-MC** [comment] 2023-08-24 01:40
No that should be plenty - it could possibly be driver or video card or your java install related?

Are you using the 64 bit version of Java? What kind of video card do you have?

**Comment by Feliixtc** [comment] 2023-08-24 01:43
Java Version: 17.0.2 64bit
card is a GTX 1080.

**Comment by Direwolf20-MC** [comment] 2023-08-24 01:45
So its really Java crashing, NOT minecraft, but of course, Minecraft runs in Java.  It *looks* like an issue with your graphics card, because the file thats crashing is nvoglv64.dll - which is nVidia related.

Could you try updating your graphics card drivers?

**Comment by Feliixtc** [comment] 2023-08-24 01:47
Yeah, looks like a new driver did come out yesterday. I'm downloading it now.

**Comment by Direwolf20-MC** [comment] 2023-08-24 01:49
Thanks! If that doesn't work I'm mostly out of ideas, except maybe doing a clean install of your drivers. I'll keep this bug report open in case others have the same issue, but no ones reported anything like this yet so its pretty weird :).

**Comment by Feliixtc** [comment] 2023-08-24 01:53
That's a negative. As far as I know, none of my mods do anything to the rendering engine. That is unless Create does something to it for all it's fancy effects.

**Comment by Direwolf20-MC** [comment] 2023-08-24 01:54
Gotcha.  Well building gadgets is calling a native to minecraft rendering call, and its the minecraft piece thats crashing, oddly enough. 

Let me know how the drive update goes! :) THANKS!

**Comment by Direwolf20-MC** [comment] 2023-08-25 00:48
As an update it looks like a few more people are having this issue now. Will keep you updated. Still seems to be a driver problem and in addition we’ve found a way to duplicate the crash in vanilla - apparently reloading textures in the end with f3-t does it? May need to go in and out of the end a couple times.

**Comment by Feliixtc** [comment] 2023-08-25 01:02
Hmm, guess that’s a good news/ bad news scenario. I did have the game crash once after updating the video driver before going to bed. 

I installed a pending Windows update overnight, but I haven’t been home again yet today to do any further troubleshooting. 

For what it’s worth, all the crashes I’ve had have been in the overworld. Also, I am using a 64 bit texture pack. If it’s reproducible in vanilla, I’m assuming neither would matter.

**Comment by Direwolf20-MC** [comment] 2023-08-25 02:03
Yea the current best guess by folks smarter than me is that this is an nvidia driver bug that is obscure in vanilla minecraft, but used more in BG2 :).

**Comment by adkinss** [comment] 2023-08-26 12:43
I am having the same issue.

Minecraft Version: 1.20.1
Mod Version: 0.1.2
Java: OpenJDK 64-Bit Server VM Zulu17.42+19-CA
Video: NVIDIA GeForce RTX 4080
Using Optifine: No

I was on driver version 536.99 (8/8) and upgraded to the latest version 537.13 (8/22) and the issue remained. 

I wasn't able to get the standard building gadget to crash, but I could get the exchanger to crash pretty reliably.  In particular, if I tried exchanging multiple blocks before they were all done, I could get it to crash when I started the 4th exchange while the first one was wrapping up.  Every once in awhile, just looking at something would cause the client to crash.

I know this could be a video driver issue, but I am not seeing this with many other 1.20.1 mods.  Something is different about this mod on 1.20.1 that is triggering it.  I haven't used 1.19.x with the mod, but I used it extensively in 1.16.5 and it never crashed.

**Comment by Direwolf20-MC** [comment] 2023-08-26 13:03
Thanks! We’re definitely lookin into it but we’ve had success causing the exact same crash in the end with vanilla. 

Related to:
https://bugs.mojang.com/browse/MC-263607

If you go into the end - kill the dragon - and do f3-A it seems to crash with the same problem. 

Do you mind trying that in vanilla? Just curious if it happens no need. 

Bg2 calls a vanilla method that’s rarely used in vanilla to do its rendering. If we can’t fix it I may have to find another way to render.

**Comment by Feliixtc** [comment] 2023-08-26 15:25
I've been able to make it back to Minecraft. After trying the vanilla end suggestion, I am even more intrigued. 

After killing the dragon, I flew around the end for 40 minutes basically spamming F3-A to no avail. I upped the render distance. I also tried leaving and re-entering the end multiple times, even respawning the dragon and going at it while reloading.

No matter how fast (or slow) I reloaded the chunks, I could not get the game to crash. Sadly, I could get modded Minecraft to crash in under 30 seconds with the gadgets.

**Comment by Direwolf20-MC** [comment] 2023-08-26 15:45
Thanks for checking - thats the problem with this bug - i've been told by some very smart folks on forgecraft that theres nothing I can do to prevent/fix it - its really just openGL and an NVidia problem.

It just so happens that BG2 is exasperating it.  Hopefully we get it sorted via other means soon

**Comment by Direwolf20-MC** [comment] 2023-08-26 18:23
I just pushed v0.1.6 that addressed a memory leak and *may* have had an impact on this bug. We can't know for sure, because of how hard it is to reproduce, but would you mind grabbing the latest bg2 and seeing if it makes this happen less by chance?

https://legacy.curseforge.com/minecraft/mc-mods/building-gadgets/files/4723411

(I just pushed it to curseforge so if its not available yet give it 5 minutes)

**Comment by adkinss** [comment] 2023-08-26 18:55
So far so good... I updated to 0.1.6 and have been using both the Building Gadget and the Exchanging Gadget with great success for awhile now... Not a single crash and I have my fingers crossed!  Thanks!

**Comment by Direwolf20-MC** [comment] 2023-08-26 19:11
Woot! Let me know if you get any crashes at all. The expectation is that you may crash less but it’s not expected to entirely resolve the issue. That said I’m crossing my fingers 🎉

**Comment by Feliixtc** [comment] 2023-08-27 01:01
Same results for me. Seems to be going stable for now. Big thumbs up.

**Comment by Direwolf20-MC** [comment] 2023-08-27 01:18
Wow glad to hear.

**Comment by adkinss** [comment] 2023-08-27 22:22
Been running with this version of the mod for a day now and we have used the building and exchanging gadgets extensively as well.  We haven't seen a single crash!  Thanks again!

**Comment by Direwolf20-MC** [comment] 2023-08-27 22:33
Awesome. I’ll close this for now. If it starts happening again please let me know.

**Closed by Direwolf20-MC** 2023-08-27 22:33 UTC

**Comment by xylix** [comment] 2023-08-30 12:20
Same problem and now installed the update, fill report back if it happens again. With quick testing didn't seem to crash now.

**Comment by Direwolf20-MC** [comment] 2023-08-30 12:55
Cool :)
