### ISSUE TITLE
Able to get around FTB claims 

### ISSUE THREAD

**Issue by deadlyaaher** [Direwolf20-MC/BuildingGadgets2#66] opened 2024-01-09 23:50 UTC
**Describe the bug**
Exchange tool and destruction tool are able to get around protection claims on servers 

**To Reproduce**
Use tools in another players claim

**Comment by MichaelHillcox** [comment] 2024-01-10 12:58
What mod version?

**Comment by jaynotgay** [comment] 2024-01-12 13:08
Maybe include abit more info like- mod version, and what actual mod your using for protection? xD

**Comment by Direwolf20-MC** [comment] 2024-02-02 03:05
Confirmed bug, need to ask FTB team how to fix :)

**Comment by Nidaelie** [comment] 2024-02-22 20:09
Any eta on fix?

**Comment by desht** [comment] 2024-02-27 16:01
Hey Dire, FTB team here :smile: 

From what I can tell (unless I've missed it somewhere), you're not currently firing Forge block place/break events before placing or breaking any blocks.  Without events, FTB Chunks can't intercept and prevent player actions in claimed chunks.

**Comment by Devilmedic** [comment] 2024-05-10 20:19
Is there any fix for this yet?

**Comment by Direwolf20-MC** [comment] 2024-06-23 16:54
Should be fixed now, thanks! Sorry for the delay!

**Closed** 2024-06-23 16:54 UTC
Labels: bug

**Comment by bishbosh69420** [comment] 2024-12-01 00:16
> Should be fixed now, thanks! Sorry for the delay!

currently using building gadgets and ftb claims in 1.20.1 and it is not working, is there some config i need to edit to allow it to work?

**Comment by Natsumi-x** [comment] 2025-03-10 02:49
> > Should be fixed now, thanks! Sorry for the delay!
> 
> currently using building gadgets and ftb claims in 1.20.1 and it is not working, is there some config i need to edit to allow it to work?

Still broken on 1.20.1. But there hasn't been an update put out on curseforge for this version of MC since last year.
